 main: Archive.h Assignment.h CanPlay.h Copy.h DiagonalWinner.h HasMove.h HorizontalWinner.h Intialization.h MakeMove.h Repository.h SwitchPlayer.h ToString.h VerticalWinner.h Winner.h Main.cpp
	g++ -o main Archive.h Assignment.h CanPlay.h Copy.h DiagonalWinner.h HasMove.h HorizontalWinner.h Intialization.h MakeMove.h Repository.h SwitchPlayer.h ToString.h VerticalWinner.h Winner.h Main.cpp

.PHONY: clean
clean:
	rm -f *.gch
